version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgres/data
    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
